# Data Manipulation 

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
path1="user_demographics.csv"

In [3]:
path2="User_product_purchase_details_p2.csv"

In [4]:
data1=pd.read_csv(path2)
data1

User_ID Product_ID City_Category Stay_In_Current_City_Years  \
0       1000001  P00069042             A                          2   
1       1000001  P00248942             A                          2   
2       1000001  P00087842             A                          2   
3       1000001  P00085442             A                          2   
4       1000002  P00285442             C                         4+   
...         ...        ...           ...                        ...   
550063  1006033  P00372445             B                          1   
550064  1006035  P00375436             C                          3   
550065  1006036  P00375436             B                         4+   
550066  1006038  P00375436             C                          2   
550067  1006039  P00371644             B                         4+   

        Marital_Status  Product_Category_1  Product_Category_2  \
0                    0                   3                 NaN   
1                    0                   1                 6.0   
2                    0                  12                 NaN   
3                    0                  12                14.0   
4                    0                   8                 NaN   
...                ...                 ...                 ...   
550063               1                  20                 NaN   
550064               0                  20                 NaN   
550065               1                  20                 NaN   
550066               0                  20                 NaN   
550067               1                  20                 NaN   

        Product_Category_3  Purchase  
0                      NaN      8370  
1                     14.0     15200  
2                      NaN      1422  
3                      NaN      1057  
4                      NaN      7969  
...                    ...       ...  
550063                 NaN       368  
550064                 NaN       371  
550065                 NaN       137  
550066                 NaN       365  
550067                 NaN       490  

[550068 rows x 9 columns]

In [5]:
data2=pd.read_csv(path1)
data2

User_ID Gender    Age  Occupation
0     1000001      F   0-17          10
1     1000002      M    55+          16
2     1000003      M  26-35          15
3     1000004      M  46-50           7
4     1000005      M  26-35          20
...       ...    ...    ...         ...
5886  1004588      F  26-35           4
5887  1004871      M  18-25          12
5888  1004113      M  36-45          17
5889  1005391      M  26-35           7
5890  1001529      M  18-25           4

[5891 rows x 4 columns]

In [6]:
df1=pd.DataFrame(data1)
df1

User_ID Product_ID City_Category Stay_In_Current_City_Years  \
0       1000001  P00069042             A                          2   
1       1000001  P00248942             A                          2   
2       1000001  P00087842             A                          2   
3       1000001  P00085442             A                          2   
4       1000002  P00285442             C                         4+   
...         ...        ...           ...                        ...   
550063  1006033  P00372445             B                          1   
550064  1006035  P00375436             C                          3   
550065  1006036  P00375436             B                         4+   
550066  1006038  P00375436             C                          2   
550067  1006039  P00371644             B                         4+   

        Marital_Status  Product_Category_1  Product_Category_2  \
0                    0                   3                 NaN   
1                    0                   1                 6.0   
2                    0                  12                 NaN   
3                    0                  12                14.0   
4                    0                   8                 NaN   
...                ...                 ...                 ...   
550063               1                  20                 NaN   
550064               0                  20                 NaN   
550065               1                  20                 NaN   
550066               0                  20                 NaN   
550067               1                  20                 NaN   

        Product_Category_3  Purchase  
0                      NaN      8370  
1                     14.0     15200  
2                      NaN      1422  
3                      NaN      1057  
4                      NaN      7969  
...                    ...       ...  
550063                 NaN       368  
550064                 NaN       371  
550065                 NaN       137  
550066                 NaN       365  
550067                 NaN       490  

[550068 rows x 9 columns]

In [7]:
df2=pd.DataFrame(data2)
df2

User_ID Gender    Age  Occupation
0     1000001      F   0-17          10
1     1000002      M    55+          16
2     1000003      M  26-35          15
3     1000004      M  46-50           7
4     1000005      M  26-35          20
...       ...    ...    ...         ...
5886  1004588      F  26-35           4
5887  1004871      M  18-25          12
5888  1004113      M  36-45          17
5889  1005391      M  26-35           7
5890  1001529      M  18-25           4

[5891 rows x 4 columns]

### Summary of datasets

In [8]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 550068 entries, 0 to 550067
Data columns (total 9 columns):
 #   Column                      Non-Null Count   Dtype  
---  ------                      --------------   -----  
 0   User_ID                     550068 non-null  int64  
 1   Product_ID                  550068 non-null  object 
 2   City_Category               550068 non-null  object 
 3   Stay_In_Current_City_Years  550068 non-null  object 
 4   Marital_Status              550068 non-null  int64  
 5   Product_Category_1          550068 non-null  int64  
 6   Product_Category_2          376430 non-null  float64
 7   Product_Category_3          166821 non-null  float64
 8   Purchase                    550068 non-null  int64  
dtypes: float64(2), int64(4), object(3)
memory usage: 37.8+ MB


In [9]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5891 entries, 0 to 5890
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   User_ID     5891 non-null   int64 
 1   Gender      5891 non-null   object
 2   Age         5891 non-null   object
 3   Occupation  5891 non-null   int64 
dtypes: int64(2), object(2)
memory usage: 184.2+ KB


Merge the above two datasets to one dataset

In [10]:
data=pd.merge(data1,data2,on='User_ID',how='right')
data.head(20)

User_ID Product_ID City_Category Stay_In_Current_City_Years  \
0   1000001  P00069042             A                          2   
1   1000001  P00248942             A                          2   
2   1000001  P00087842             A                          2   
3   1000001  P00085442             A                          2   
4   1000001  P00085942             A                          2   
5   1000001  P00102642             A                          2   
6   1000001  P00110842             A                          2   
7   1000001  P00004842             A                          2   
8   1000001  P00117942             A                          2   
9   1000001  P00258742             A                          2   
10  1000001  P00142242             A                          2   
11  1000001  P00000142             A                          2   
12  1000001  P00297042             A                          2   
13  1000001  P00059442             A                          2   
14  1000001   P0096542             A                          2   
15  1000001  P00184942             A                          2   
16  1000001  P00051842             A                          2   
17  1000001  P00214842             A                          2   
18  1000001  P00165942             A                          2   
19  1000001  P00111842             A                          2   

    Marital_Status  Product_Category_1  Product_Category_2  \
0                0                   3                 NaN   
1                0                   1                 6.0   
2                0                  12                 NaN   
3                0                  12                14.0   
4                0                   2                 4.0   
5                0                   4                 8.0   
6                0                   1                 2.0   
7                0                   3                 4.0   
8                0                   5                15.0   
9                0                   5                 NaN   
10               0                   8                 NaN   
11               0                   3                 4.0   
12               0                   8                 NaN   
13               0                   6                 8.0   
14               0                   3                 4.0   
15               0                   1                 8.0   
16               0                   4                 8.0   
17               0                  14                 NaN   
18               0                   8                 NaN   
19               0                   8                 NaN   

    Product_Category_3  Purchase Gender   Age  Occupation  
0                  NaN      8370      F  0-17          10  
1                 14.0     15200      F  0-17          10  
2                  NaN      1422      F  0-17          10  
3                  NaN      1057      F  0-17          10  
4                  8.0     12842      F  0-17          10  
5                  9.0      2763      F  0-17          10  
6                  5.0     11769      F  0-17          10  
7                 12.0     13645      F  0-17          10  
8                  NaN      8839      F  0-17          10  
9                  NaN      6910      F  0-17          10  
10                 NaN      7882      F  0-17          10  
11                 5.0     13650      F  0-17          10  
12                 NaN      7839      F  0-17          10  
13                16.0     16622      F  0-17          10  
14                12.0     13627      F  0-17          10  
15                17.0     19219      F  0-17          10  
16                 NaN      2849      F  0-17          10  
17                 NaN     11011      F  0-17          10  
18                 NaN     10003      F  0-17          10  
19                 NaN      8094      F  0-17          10

In [11]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 550068 entries, 0 to 550067
Data columns (total 12 columns):
 #   Column                      Non-Null Count   Dtype  
---  ------                      --------------   -----  
 0   User_ID                     550068 non-null  int64  
 1   Product_ID                  550068 non-null  object 
 2   City_Category               550068 non-null  object 
 3   Stay_In_Current_City_Years  550068 non-null  object 
 4   Marital_Status              550068 non-null  int64  
 5   Product_Category_1          550068 non-null  int64  
 6   Product_Category_2          376430 non-null  float64
 7   Product_Category_3          166821 non-null  float64
 8   Purchase                    550068 non-null  int64  
 9   Gender                      550068 non-null  object 
 10  Age                         550068 non-null  object 
 11  Occupation                  550068 non-null  int64  
dtypes: float64(2), int64(5), object(5)
memory usage: 54.6+ MB


### Describing the numerical and categorical data


describing the numerical data gives you statistical details like percentile,mean,std etc

In [12]:
df=pd.DataFrame(data)

In [13]:
df.describe()

User_ID  Marital_Status  Product_Category_1  Product_Category_2  \
count  5.500680e+05   550068.000000       550068.000000       376430.000000   
mean   1.003029e+06        0.409653            5.404270            9.842329   
std    1.727592e+03        0.491770            3.936211            5.086590   
min    1.000001e+06        0.000000            1.000000            2.000000   
25%    1.001516e+06        0.000000            1.000000            5.000000   
50%    1.003077e+06        0.000000            5.000000            9.000000   
75%    1.004478e+06        1.000000            8.000000           15.000000   
max    1.006040e+06        1.000000           20.000000           18.000000   

       Product_Category_3       Purchase     Occupation  
count       166821.000000  550068.000000  550068.000000  
mean            12.668243    9263.968713       8.076707  
std              4.125338    5023.065394       6.522660  
min              3.000000      12.000000       0.000000  
25%              9.000000    5823.000000       2.000000  
50%             14.000000    8047.000000       7.000000  
75%             16.000000   12054.000000      14.000000  
max             18.000000   23961.000000      20.000000

describing the categorical data gives you details like top,frequency,count etc

In [14]:
df['Product_ID'].describe()

count        550068
unique         3631
top       P00265242
freq           1880
Name: Product_ID, dtype: object

In [15]:
df['City_Category'].describe()

count     550068
unique         3
top            B
freq      231173
Name: City_Category, dtype: object

In [16]:
df['Stay_In_Current_City_Years'].describe()

count     550068
unique         5
top            1
freq      193821
Name: Stay_In_Current_City_Years, dtype: object

In [17]:
df['Gender'].describe()

count     550068
unique         2
top            M
freq      414259
Name: Gender, dtype: object

In [18]:
df['Age'].describe()

count     550068
unique         7
top        26-35
freq      219587
Name: Age, dtype: object

lets know about the unique values present in every column

In [19]:
data['Product_ID'].unique()

array(['P00069042', 'P00248942', 'P00087842', ..., 'P00013442',
       'P00063442', 'P00315242'], dtype=object)

In [20]:
data['City_Category'].unique()

array(['A', 'C', 'B'], dtype=object)

In [21]:
data['Stay_In_Current_City_Years'].unique()

array(['2', '4+', '3', '1', '0'], dtype=object)

In [22]:
data.groupby('Stay_In_Current_City_Years')['Stay_In_Current_City_Years'].count()

Stay_In_Current_City_Years
0      74398
1     193821
2     101838
3      95285
4+     84726
Name: Stay_In_Current_City_Years, dtype: int64

In [23]:
data['Marital_Status'].unique()

array([0, 1], dtype=int64)

In [24]:
data.groupby('Marital_Status')['Marital_Status'].count()

Marital_Status
0    324731
1    225337
Name: Marital_Status, dtype: int64

In [25]:
objectcat1=data['Product_Category_1'].unique()
objectcat1

array([ 3,  1, 12,  2,  4,  5,  8,  6, 14, 16, 20, 18, 11,  7, 15, 19, 17,
       13, 10,  9], dtype=int64)

In [26]:
data.groupby('Product_Category_1')['Product_Category_1'].count()

Product_Category_1
1     140378
2      23864
3      20213
4      11753
5     150933
6      20466
7       3721
8     113925
9        410
10      5125
11     24287
12      3947
13      5549
14      1523
15      6290
16      9828
17       578
18      3125
19      1603
20      2550
Name: Product_Category_1, dtype: int64

In [27]:
data['Product_Category_2'].unique()

array([nan,  6., 14.,  4.,  8.,  2., 15., 17., 16.,  5., 11., 13., 18.,
       12.,  3.,  9., 10.,  7.])

In [28]:
data.groupby('Product_Category_2')['Product_Category_2'].count()

Product_Category_2
2.0     49217
3.0      2884
4.0     25677
5.0     26235
6.0     16466
7.0       626
8.0     64088
9.0      5693
10.0     3043
11.0    14134
12.0     5528
13.0    10531
14.0    55108
15.0    37855
16.0    43255
17.0    13320
18.0     2770
Name: Product_Category_2, dtype: int64

In [29]:
data['Product_Category_3'].unique()

array([nan, 14.,  8.,  9.,  5., 12., 16., 17., 15., 13., 18.,  6., 10.,
       11.,  4.,  3.])

In [30]:
data.groupby('Product_Category_3')['Product_Category_3'].count()

Product_Category_3
3.0       613
4.0      1875
5.0     16658
6.0      4890
8.0     12562
9.0     11579
10.0     1726
11.0     1805
12.0     9246
13.0     5459
14.0    18428
15.0    28013
16.0    32636
17.0    16702
18.0     4629
Name: Product_Category_3, dtype: int64

In [31]:
data['Gender'].unique()

array(['F', 'M'], dtype=object)

In [32]:
data.groupby('Gender')['Gender'].count()

Gender
F    135809
M    414259
Name: Gender, dtype: int64

In [33]:
data['Age'].unique()

array(['0-17', '55+', '26-35', '46-50', '51-55', '36-45', '18-25'],
      dtype=object)

In [34]:
data.groupby('Age')['Age'].count()

Age
0-17      15102
18-25     99660
26-35    219587
36-45    110013
46-50     45701
51-55     38501
55+       21504
Name: Age, dtype: int64

In [35]:
data['Occupation'].unique()

array([10, 16, 15,  7, 20,  9,  1, 12, 17,  0,  3,  4, 11,  8, 19,  2, 18,
        5, 14, 13,  6], dtype=int64)

In [36]:
data.groupby('Occupation')['Occupation'].count()

Occupation
0     69638
1     47426
2     26588
3     17650
4     72308
5     12177
6     20355
7     59133
8      1546
9      6291
10    12930
11    11586
12    31179
13     7728
14    27309
15    12165
16    25371
17    40043
18     6622
19     8461
20    33562
Name: Occupation, dtype: int64

# Task1-Maximum, spend in different categories of products

product_category_1

In [37]:
data.groupby('Product_Category_1').sum()['Purchase']

Product_Category_1
1     1910013754
2      268516186
3      204084713
4       27380488
5      941835229
6      324150302
7       60896731
8      854318799
9        6370324
10     100837301
11     113791115
12       5331844
13       4008601
14      20014696
15      92969042
16     145120612
17       5878699
18       9290201
19         59378
20        944727
Name: Purchase, dtype: int64

product_category_1

In [38]:
data.groupby('Product_Category_2').sum()['Purchase']

Product_Category_2
2.0     670303864
3.0      32402777
4.0     262295485
5.0     236844899
6.0     189417477
7.0       4309812
8.0     658392656
9.0      41428000
10.0     47619084
11.0    126366165
12.0     38560412
13.0    101975384
14.0    391556939
15.0    392067176
16.0    445339722
17.0    125495400
18.0     25906260
Name: Purchase, dtype: int64

In [39]:
data.groupby('Product_Category_3').sum()['Purchase']

Product_Category_3
3.0       8545034
4.0      18364475
5.0     201858094
6.0      64520181
8.0     163619031
9.0     120788622
10.0     23311034
11.0     21825045
12.0     80583631
13.0     71977563
14.0    185249212
15.0    345662769
16.0    391040983
17.0    196581588
18.0     50891137
Name: Purchase, dtype: int64

# Based on above data which set of customers can be offered personalised discount vouchers


Based on age analyze the purchase rate

In [40]:
data.groupby("Age").sum()['Purchase']


Age
0-17      134913183
18-25     913848675
26-35    2031770578
36-45    1026569884
46-50     420843403
51-55     367099644
55+       200767375
Name: Purchase, dtype: int64

Based on city analyze the purchase rate

In [41]:
data.groupby("City_Category").sum()['Purchase']

City_Category
A    1316471661
B    2115533605
C    1663807476
Name: Purchase, dtype: int64

Based on gender analyze the purchase rate

In [42]:
data.groupby("Gender").sum()['Purchase']

Gender
F    1186232642
M    3909580100
Name: Purchase, dtype: int64

Based on occupation analyze the purchase rate

In [43]:
data.groupby("Occupation").sum()['Purchase']

Occupation
0     635406958
1     424614144
2     238028583
3     162002168
4     666244484
5     113649759
6     188416784
7     557371587
8      14737388
9      54340046
10    115844465
11    106751618
12    305449446
13     71919481
14    259454692
15    118960211
16    238346955
17    393281453
18     60721461
19     73700617
20    296570442
Name: Purchase, dtype: int64

Based on Marital_Status analyze the purchase rate


In [44]:
data.groupby("Marital_Status").sum()['Purchase']

Marital_Status
0    3008927447
1    2086885295
Name: Purchase, dtype: int64

In [45]:
data1 = df.groupby('Age')['Product_ID'].apply(lambda x: x.value_counts().index[0]).reset_index()
data1

Age Product_ID
0   0-17  P00255842
1  18-25  P00265242
2  26-35  P00265242
3  36-45  P00025442
4  46-50  P00265242
5  51-55  P00265242
6    55+  P00265242

In [46]:
df["Product_ID"].value_counts(sort=True)[:10]

P00265242    1880
P00025442    1615
P00110742    1612
P00112142    1562
P00057642    1470
P00184942    1440
P00046742    1438
P00058042    1422
P00145042    1406
P00059442    1406
Name: Product_ID, dtype: int64

# Based on above data which set of customers can be offered personalised discount vouchers

the personalised discount vouchers are provide to those customers whose age lies in between 26-35 irrespective of their gender and occupation




# And in which category the voucher should be offered

the voucher is apllicable on the prodcut category where the product_id is P00265242 

# Or it should be on the total amount

yes, we can provide the discount on total amount for the top 10 active users.
